create table if not exists public.operations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_date date not null default current_date,
  type text not null check (type in ('Доход','Расход')),
  category text not null,
  payment text,
  amount numeric(14,2) not null check (amount > 0),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists operations_user_date_idx on public.operations(user_id, operation_date desc);
alter table public.operations enable row level security;

drop policy if exists "authenticated users manage operations" on public.operations;
drop policy if exists "rayhan public read" on public.operations;
drop policy if exists "rayhan public insert" on public.operations;
drop policy if exists "rayhan public delete" on public.operations;

authorization
-- Доступ только владельцу записи.
create policy "users read own operations" on public.operations for select to authenticated
using ((select auth.uid()) = user_id);
create policy "users insert own operations" on public.operations for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "users update own operations" on public.operations for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "users delete own operations" on public.operations for delete to authenticated
using ((select auth.uid()) = user_id);
