import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;const sb=url&&key?createClient(url,key):null;
const cats={Доход:['Наличные','Карта','Переводы','Доставка'],Расход:['Продукты','Зарплата','Аренда','Коммунальные','Хозяйственные','Закупки','Прочее']};
function App(){const [items,setItems]=useState([]),[type,setType]=useState('Доход'),[cat,setCat]=useState('Наличные'),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[tab,setTab]=useState('Главная'),[msg,setMsg]=useState('');
useEffect(()=>{if(sb)load();else setItems(JSON.parse(localStorage.getItem('rayhan_ops')||'[]'))},[]);
async function load(){const{data,error}=await sb.from('operations').select('*').order('operation_date',{ascending:false}).order('id',{ascending:false});if(error)setMsg('Ошибка Supabase: '+error.message);else setItems(data||[])}
function changeType(v){setType(v);setCat(cats[v][0])}
async function add(){let a=Number(amount);if(!a||a<=0)return setMsg('Введите сумму');let x={operation_date:date,type,category:cat,amount:a,note,created_at:new Date().toISOString()};if(sb){let{error}=await sb.from('operations').insert(x);if(error)return setMsg(error.message);await load()}else{const all=[{...x,id:Date.now()},...items];setItems(all);localStorage.setItem('rayhan_ops',JSON.stringify(all))}setAmount('');setNote('');setMsg('Операция сохранена ✓')}
function del(id){const all=items.filter(x=>x.id!==id);setItems(all);localStorage.setItem('rayhan_ops',JSON.stringify(all))}
const today=new Date().toISOString().slice(0,10),inc=items.filter(x=>x.type==='Доход'&&x.operation_date===today).reduce((s,x)=>s+Number(x.amount),0),exp=items.filter(x=>x.type==='Расход'&&x.operation_date===today).reduce((s,x)=>s+Number(x.amount),0);
const totalInc=items.filter(x=>x.type==='Доход').reduce((s,x)=>s+Number(x.amount),0),totalExp=items.filter(x=>x.type==='Расход').reduce((s,x)=>s+Number(x.amount),0);
return <div className="app"><aside><h1>☕ РАЙХАН</h1><small>ФИНАНСОВАЯ СИСТЕМА</small>{['Главная','Новая операция','Операции','Отчёты'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<div className="offline">v1.0<br/>Отчётность чайханы</div></aside><main>{tab==='Главная'&&<><h2>Финансовая панель</h2><p>Сегодня, {new Date().toLocaleDateString('ru-RU')}</p><section className="cards"><Card t="Доход сегодня" v={inc}/><Card t="Расход сегодня" v={exp}/><Card t="Чистая прибыль" v={inc-exp}/><Card t="Всего операций" v={items.length} raw/></section><h3>Последние операции</h3><Table items={items.slice(0,8)} del={del}/></>}
{tab==='Новая операция'&&<div className="form"><h2>Новая операция</h2><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Тип<select value={type} onChange={e=>changeType(e.target.value)}><option>Доход</option><option>Расход</option></select></label><label>Категория<select value={cat} onChange={e=>setCat(e.target.value)}>{cats[type].map(x=><option>{x}</option>)}</select></label><label>Сумма, ₽<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label><label>Комментарий<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Необязательно"/></label><button className="save" onClick={add}>СОХРАНИТЬ ОПЕРАЦИЮ</button>{msg&&<div className="msg">{msg}</div>}</div>}
{tab==='Операции'&&<><h2>Все операции</h2><Table items={items} del={del}/></>}
{tab==='Отчёты'&&<><h2>Общий отчёт</h2><section className="cards"><Card t="Все доходы" v={totalInc}/><Card t="Все расходы" v={totalExp}/><Card t="Общая прибыль" v={totalInc-totalExp}/></section><h3>Структура расходов и доходов</h3>{Object.entries(items.reduce((a,x)=>{a[x.category]=(a[x.category]||0)+Number(x.amount);return a},{})).map(([k,v])=><div className="line"><span>{k}</span><b>{v.toLocaleString('ru-RU')} ₽</b></div>)}</>}</main></div>}
function Card(p){return <div className="card"><span>{p.t}</span><strong>{p.raw?p.v:p.v.toLocaleString('ru-RU')+' ₽'}</strong></div>}
function Table({items,del}){return <div className="table">{items.length===0?<p>Операций пока нет.</p>:items.map(x=><div className="tr"><span>{x.operation_date}</span><span className={x.type==='Доход'?'income':'expense'}>{x.type}</span><span>{x.category}</span><b>{Number(x.amount).toLocaleString('ru-RU')} ₽</b><button onClick={()=>del(x.id)}>×</button></div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);