import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const dishes=[['Плов по-узбекски',480,10],['Шурпа из баранины',520,10],['Лагман',490,15],['Манты',460,25],['Самса',180,15],['Лепёшка',90,7],['Чайник чая',260,7],['Компот',120,3]];
const money=n=>Number(n||0).toLocaleString('ru-RU')+' ₽';
function App(){const[tab,setTab]=useState('pos'),[cart,setCart]=useState([]),[orders,setOrders]=useState([]),[code,setCode]=useState(''),[user,setUser]=useState(null),[table,setTable]=useState(8),[msg,setMsg]=useState('');function add(d){setCart(c=>[...c,d])}function send(){if(!cart.length)return setMsg('Добавьте блюда в заказ');const now=Date.now(),total=cart.reduce((s,x)=>s+x[1],0),items=cart.map(x=>({name:x[0],price:x[1],mins:x[2],readyAt:now+x[2]*60000}));setOrders(o=>[{id:Date.now(),table,total,items,status:'cooking'},...o]);setCart([]);setMsg('Заказ отправлен на кухню и сразу взят в работу')}if(!user)return <div className="login"><div className="loginbox"><h1>САБР</h1><p>POS • Чайхана</p><input value={code} onChange={e=>setCode(e.target.value)} maxLength="4" placeholder="Код сотрудника"/><button onClick={()=>{if(['1111','2222','3333'].includes(code))setUser(code==='1111'?'Владелец':code==='2222'?'Официант':'Повар');else setMsg('Код: 1111, 2222 или 3333')}}>Войти</button><small>1111 — владелец · 2222 — официант · 3333 — повар</small>{msg&&<div className="msg">{msg}</div>}</div></div>;return <div className="app"><aside><h1>САБР</h1><small>ЧАЙХАНА • POS</small>{['pos','kitchen','tables','reports','staff'].map((x,i)=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{['Заказы','Кухня','Столы','Отчёты','Сотрудники'][i]}</button>)}<div className="user">{user}<br/><button onClick={()=>setUser(null)}>Выйти</button></div></aside><main><header><div><h2>{tab==='pos'?'Новый заказ':tab==='kitchen'?'Кухня':tab==='tables'?'План зала':tab==='reports'?'Отчёты':'Сотрудники'}</h2><small>Облачная версия • САБР</small></div></header>{tab==='pos'&&<div className="pos"><section className="card"><h3>Стол</h3><select value={table} onChange={e=>setTable(+e.target.value)}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>Стол {i+1}</option>)}</select><h3>Меню</h3><div className="menu">{dishes.map((d,i)=><button className="dish" onClick={()=>add(d)} key={i}><b>{d[0]}</b><span>{money(d[1])}</span><small>готовка ~{d[2]} мин</small></button>)}</div></section><section className="card cart"><h3>Заказ · Стол {table}</h3>{cart.map((x,i)=><div className="row" key={i}><span>{x[0]}</span><b>{money(x[1])}</b></div>)}<div className="total">{money(cart.reduce((s,x)=>s+x[1],0))}</div><button className="primary" onClick={send}>Отправить на кухню</button><button onClick={()=>setCart([])}>Очистить</button>{msg&&<div className="msg">{msg}</div>}</section></div>}{tab==='kitchen'&&<Kitchen orders={orders} setOrders={setOrders}/>} {tab==='tables'&&<Tables/>}{tab==='reports'&&<Reports orders={orders}/>} {tab==='staff'&&<Staff/>}</main></div>}
function Kitchen({orders,setOrders}){const[,tick]=useState(0);React.useEffect(()=>{const t=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(t)},[]);return <div className="grid">{orders.filter(o=>o.status==='cooking').map(o=><div className="card order" key={o.id}><h3>Стол {o.table}</h3>{o.items.map((i,n)=>{const left=i.readyAt-Date.now(),min=Math.max(0,Math.floor(left/60000)),sec=Math.max(0,Math.floor(left/1000)%60);return <div className="row" key={n}><span><b>{i.name}</b><small>норма ~{i.mins} мин</small></span><b className={left<=0?'late':''}>{left<=0?'Время вышло':min+':'+String(sec).padStart(2,'0')}</b></div>})}<button className="primary" onClick={()=>setOrders(xs=>xs.map(x=>x.id===o.id?{...x,status:'ready'}:x))}>Все блюда готовы</button></div>)}{orders.filter(o=>o.status==='ready').map(o=><div className="card" key={o.id}><h3>Стол {o.table} · ГОТОВ</h3><button onClick={()=>setOrders(xs=>xs.filter(x=>x.id!==o.id))}>Выдан клиенту</button></div>)}{!orders.length&&<div className="card">Заказов на кухне пока нет.</div>}</div>}
function Tables(){return <div className="tables">{Array.from({length:12},(_,i)=><div className="table" key={i}>Стол {i+1}<small>{i%3===0?'Занят':'Свободен'}</small></div>)}</div>}
function Reports({orders}){const rev=orders.reduce((s,o)=>s+o.total,0);return <div className="cards"><div className="card"><small>Заказов</small><strong>{orders.length}</strong></div><div className="card"><small>Выручка демо</small><strong>{money(rev)}</strong></div><div className="card"><small>В работе</small><strong>{orders.filter(o=>o.status==='cooking').length}</strong></div></div>}
function Staff(){return <div className="card"><h3>Сотрудники</h3><p>1111 — Владелец</p><p>2222 — Официант</p><p>3333 — Повар</p><hr/><p>Повар получает заказ сразу со статусом «Готовится» и видит обратный таймер по каждому блюду.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
